# Generated by Django 3.2.12 on 2022-10-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221030_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='name1',
            new_name='POCname',
        ),
        migrations.RemoveField(
            model_name='crossopen',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='name3',
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='Format',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='OutroundSpoken',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='POB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='Size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='TournamentName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='Year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adjudicators',
            name='awards',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamSlots',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
