# Generated by Django 3.2.12 on 2022-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crossopen_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicators',
            name='contactno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='crossopen',
            name='contactno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='contactno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
