# Generated by Django 3.2.12 on 2022-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221104_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='contactno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
