# Generated by Django 3.2.12 on 2022-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teams_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicators',
            name='Format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='OutroundSpoken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='POB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='Size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='TournamentName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='Year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='awards',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicators',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
