# Generated by Django 3.2.12 on 2022-11-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20221104_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='POCname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
