# Generated by Django 3.2.12 on 2022-10-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221030_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossopen',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
