# Generated by Django 3.2.12 on 2022-11-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221103_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='contactno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='teamSlots',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
