# Generated by Django 3.2.12 on 2022-11-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20221104_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjudicators',
            name='contactno',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='crossopen',
            name='contactno',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='contactno',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
